### ISSUE TITLE
Thread safety and Webrick

### ISSUE THREAD

**Issue by repinel** [rails/activeresource#178]
#167 introduced thread safety to some attributes like `site`. With Webrick, if you have something like:

```ruby
class Person < ActiveResource::Base
  self.site = 'https://api.people.com'
end
```

`site` is not set for the main thread, only current ones. Meaning that the first `activeresource` usage goes fine, but the followings fail with `Missing site URI` from [connection.rb#35](https://github.com/rails/activeresource/blob/e51a2a912d1149ec1edf55208a9a2a570697192f/lib/active_resource/connection.rb#L35).

**Comment by craigsheen** [comment]
Just run in to this problem myself. reverted my version back.

**Comment by rafaelfranca** [comment]
hmmm. I don't know how webrick works. @tenderlove @matthewd any idea what could be causing this?

cc @peterjm

**Comment by peterjm** [comment]
I'm not sure that this is a Webrick-only issue.

> site is not set for the main thread, only current ones

That's the intentional behaviour of [this code](
https://github.com/rails/activeresource/blob/006b1c9577fca271152cebd2cb7962947fd331d9/lib/active_resource/threadsafe_attributes.rb#L37-L39); it makes the assumption that child threads should inherit configuration from the main thread, but that the main thread shouldn't inherit configuration from a child thread.

If that assumption isn't valid (or it causes significant backwards compatibility problems), that's a problem.

We *could* modify the attribute setting by attempting to update the value in the main thread when a child thread sets its value; that value would then be inherited by future child threads, who would be responsible for setting their own correct values before making any requests...

**Comment by rafaelfranca** [comment]
@repinel @craigsheen are you able to reproduce this behavior in production or only in development?

**Comment by repinel** [comment]
@rafaelfranca I had the issue running in development mode, but I can try in production later.

**Comment by rafaelfranca** [comment]
I believe that in production it will be not a problem since the code will be eager loaded before the first children thread is created. In development it happens because the code is only loaded when it is needed and that will be after the children thread is created.

**Comment by repinel** [comment]
@rafaelfranca As you suspected, this is not an issue in production with eager load.

**Comment by repinel** [comment]
This is no longer an issue running Rails 5 in the same conditions as before: development, with Webrick, and eager load off.
