### ISSUE TITLE
activeresource does not support rails 5.0.beta3

### ISSUE THREAD

**Issue by limbo-lab** [rails/activeresource#213]
I have this in my Gemfile
```ruby
gem 'activeresource', github: 'rails/activeresource', branch: 'master'
```

yet complains:
```
Resolving dependencies....
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    active_model_serializers (~> 0.10.0.rc1) was resolved to 0.10.0.rc4, which depends on
      activemodel (>= 4.0)

    activeresource was resolved to 5.0.0, which depends on
      activemodel-serializers-xml (~> 1.0) was resolved to 1.0.0, which depends on
        activemodel (> 5.x)

    activeresource was resolved to 5.0.0, which depends on
      activemodel (~> 5.x)

    rails (< 5.1, >= 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
      activemodel (= 5.0.0.beta3)

    rails (< 5.1, >= 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
      activemodel (= 5.0.0.beta3)

    activeresource was resolved to 5.0.0, which depends on
      rails-observers (~> 0.1.2) was resolved to 0.1.2, which depends on
        activemodel (~> 4.0)
```

**Comment by eileencodes** [comment]
Are you running `bundle` or `bundle update`?

We're using activeresource with Rails 5 so it is supported. I don't recommend doing a `bundle update` as a lot of dependencies aren't necessarily caught up. 

It looks like you need to update `rails-observers` first since that's pointing to `activemodel (~> 4.0)` but master is allows Rails 5. `active_model_serializers` as well is not pointing a version that supports Rails 5. That gem is owned by rails-api (https://github.com/rails-api/active_model_serializers) and doesn't look like it's been updated. So the problem is that you have dependencies that depend on older versions of Rails, this is not solely a problem with `activeresource`

**Comment by limbo-lab** [comment]
Resolved by add `rails-observer` explicitly

```
gem 'active_model_serializers', '~> 0.10.0.rc4'
gem 'mysql2'
gem 'spreadsheet'
gem 'rails-observers', github: 'rails/rails-observers'
gem 'activeresource', github: 'rails/activeresource'
```
Thinks.
